### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext-projects#1]
I'd like to have "badges" information for each project.

Possible badges might include:
WeBWorK
AIM-approved
Won an award
Has instructor guide
Has solution manual
Has reading questions  (is that badge-worthy, or is it just something I always push?)

**Comment by rbeezer** [comment]
Good idea.  I'd call those **features**, which mostly get rendered as badges.

Except "award" - maybe that should be a blurb like the current "description"?  It should have some content - award name, purpose, cash value, etc, etc.  But it's presence (or an attribute) could be the signal for a blue-ribbon badge, or similar.

I'm going to version the (implied) schema.  I'll try to dealy version 2 for a bit if there is more to add here.

> or is it just something I always push?

I thought **I** always pushed it!  ;-)

**Comment by rbeezer** [comment]
We have info that could be presented as badges, plus a bit more.  We can continue to iterate on issues as needed.
