### ISSUE TITLE
copyright holder

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext-projects#12]
Should a project have a place where copyright holder can be named? This is not always the author. And depending on the license, maybe someone will want to contact the copyright holder.

**Comment by rbeezer** [comment]
Thanks for all the suggestions, which I am finally getting back to.  The purpose of this database is to make the depth and breadth of PreTeXt evident.  It is promotion for PreTeXt itself, but is also promotion for authors' projects, which will increase teh visibility of PreTeXt.

So, for example, the number/extent of **open** textbooks is an important part of what is being communicated.  In other words, "PreTeXt is designed to make open textbooks possible and is meeting this goal", even when there is no **requirement** for licenses on output.  So licenses are noted and tabulated.

On the flip side, I want to leave a lot of details to the authors/publishers/copyright holders to maintain via their landing page.  This is not meant to be a comprehensive bibliographic record/database.

So I'd like to leave this one for the project to communicate.
