### ISSUE TITLE
Get ready for initial release

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext-projects#2]
We can announce the Projects repository as soon as we tweak the
format of the data file and update the instructions.

The instructions should say to use 
   src/beezer-FCLA.xml
as a model.

Can we get this ready for Monday's April newsletter?

**Comment by rbeezer** [comment]
I'd like to have at least a simple version of output implemented as part of defining/refining the XML structure.   Do you think previous suggestions could be called features, and that any awards deserve more explanation, and thus should be more like a paragraph?

**Comment by rbeezer** [comment]
Announced, and have initial contributions via PR #3 and #4, so I'll close this.
