### ISSUE TITLE
Missing books

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext-projects#20]
Some PreTeXt books which may not have been submitted yet.

http://mhcc.edu/Faculty/ActivePreCalc/output/html/precalc1-MHCC.html

http://www.jiblm.org/mahavier/discrete/html/
(Ted may also have two other PreTeXt books.)

**Comment by rbeezer** [comment]
I've got these on my hit list now.  Thanks.

Rob
