### ISSUE TITLE
add video feature

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext-projects#28]
Some authors have videos (or screencasts, or whatever) that go along with their books - sometimes quite detailed.  I think the "feature" category should have this, although I'm not sure whether it should also include hosting service e.g. youtube, vimeo ...

**Comment by rbeezer** [comment]
Yes!

**Comment by rbeezer** [comment]
This was done on 62685e5325a3403cfdd31adefa99291c958b9566
