### ISSUE TITLE
Accessible flag for next iteration

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-projects#5]
Let authors flag a book as "highly accessible" - in other words, additional work beyond default PreTeXt that comes for free.  Such as,

* Good "alt text" via the `description` element of an `image`.
* Careful use of color (as in diagrams).
* No interactives that trap focus, etc.
* More?

**Comment by davidfarmer** [comment]
After the current effort to help people make a better index,
I was thing that a Proper Use of Alt Text seminar would be
useful.

**Comment by rbeezer** [comment]
Good idea.  Maybe just a bit broader?

"What A PTX Author Can Do to Make Their Text Highly Accessible"

Though I agree that alt-text might be the biggest hurdle.

**Comment by rbeezer** [comment]
We now have `features/@accessible`, complete with a badge. so closing.
