### ISSUE TITLE
Janssen rings book needs new URL

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext-projects#53]
https://ringswithinquiry.org/ - but I think @mkjanssen should probably do it rather than me since I'll probably mess something subtle up.

**Comment by kcrisman** [comment]
See also https://github.com/mkjanssen/IBL-modernalgebra

**Comment by rbeezer** [comment]
Completed at 6020d3ef4a03a7a18c097c36dadc07c0d72723b2
